refresh.py

1. Changed the coordinates of ways: With that we will use the coordinates of the objects center instead of the first node.
2. Added another elif for the Overpass request status. If there is a "Bad request" there will be an output on the console (this is helpful if you make changes at the Overpass request).
3. I split the string for the Overpass request. That way it's easier to understand and to adjust the request.

center coordinates + optimization Overpass request

---

css/style.css
index.html
js/veggiemap-icons.js
refresh.py

1. Cleanup / code prettify
2. Add emoji to the title (I hope you like it)

Cleanup + Emoji

---

css/style.css
js/veggiemap.js

1. x replaced by brackets in the legend as suggested in # 34.
2. Adjust the size of the layer button to the other buttons.

brackets in the legend + legend button size

---

index.html
manifest.json
service-worker.js

With that it's easy to install the website as an app on a mobile. Tested with Android.

Step to Progressive Web App

---

index.html
js/veggiemap-icons.js
js/veggiemap.js
refresh.py
service-worker.js

It's better to avoid var [1].
[1] https://wiki.selfhtml.org/wiki/JavaScript/Variable/let#Verwendung

'var' replaced by 'let' and 'const' + removed type="text/css" + viewport settings

---

README.md
css/style.css
index.html
refresh.py

I changed the design of the popup box. I use emojis instead of words.
Before:
After:
The phone number now is clickable :-)

Redesign of the popup box + minor changes

---

css/style.css
js/veggiemap.js
refresh.py

Like the website openstreetmap.org. Maybe we could introduce a settings page where you can choose between right and left. I'll put this on my personal todo list.

Put buttons to the right + Fix info box for small devices + Remove unnecessary slashes

---

refresh.py

There are also some relations with `diet:vegan` and `diet:vegetarian` tags.

Add relations also

---

refresh.py

In some countries are a lot places without a name tag but with english names (key is `name:en`). So I think it's better to take these instead build a name from the type and the id.

Take english name as alternative

---

refresh.py

There seem to be a lot of different address systems in the world. It's going to be difficult to adequately display all of them in the popup box, but this should at least help a little in some regions.

Use suburb as alternative

---

css/style.css
index.html
js/veggiemap.js

Add spinner

---

data/taginfo.json

Add `taginfo.json` to get listed on taginfo [1][2].
[1] https://taginfo.openstreetmap.org
[2] https://wiki.openstreetmap.org/wiki/Taginfo/Projects

Add taginfo

---

how-to/style.css
how-to/tutorial_de.html

- separate CSS file
- reformulation (like address third person)
- additions
- list the keys

Rework How-To

---

css/style.css
index.html

In fullscreen mode the infobox was not displayed.

Fix info box issue in fullscreen

---

refresh.py

Increase overpass query timeout

---

js/veggiemap.js
refresh.py

The goal is just to have a clearer code.

A bit linting and refactoring

---

js/veggiemap.js
refresh.py

Add pagename support for Facebook and Instagram

---

README.md
css/datacheck.css
data/urldata.json
datacheck/datacheck.py
datacheck/datacheck_table.html
datacheck/index.html
how-to/tutorial_de.html
js/datacheck-table.js
js/datacheck.js

This adds a map and a table as tools to improve data quality. What do you think about it?
To start the data check, `./datacheck/datacheck.py` must be executed. Since this is a larger process, I would recommend doing this only once a day.

Introduce data validation

---

datacheck/datacheck.py

I tried to get the cron job to run on Debian. I had to do two things to make it work:
1. Fix path of script interpreter to python3
2. Manually make the script executable: `sudo chmod +x datacheck.py`
I hope this fixes the issue 🚀

Fix path of script interpreter

---

.eslintrc.json
.prettierrc.json
.stylelintrc.json
data/urldata.json
datacheck/datacheck.py
package-lock.json
package.json

All are minor changes :slightly_smiling_face:

Update dependencies, Fix check issue, Add mobile tag check

---

how-to/tutorial_it.html
js/veggiemap.js
locales/it.json
third-party/leaflet.languageselector/README.md
third-party/leaflet.languageselector/images/image_info.md
third-party/leaflet.languageselector/images/it.svg

I have added italian translations:
- strings: it.json
- menus
- html tutorial

Added italian translations
